[server]
maxUploadSize = 20
runOnSave = true

[theme]
primaryColor = "#2563eb"
backgroundColor = "#C8DCFF"
secondaryBackgroundColor = "#C8DCFF"
textColor = "#0f172a"
font = "sans serif"
base = "light"
